# fly.toml app configuration file generated for muthurgpt on 2024-01-08T11:17:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muthurgpt"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
